car_collection/models.py
from enum import unique
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from datetime import datetime
import uuid


from werkzeug.security import generate_password_hash, check_password_hash


import secrets


from flask_login import LoginManager, UserMixin

from flask_marshmallow import Marshmallow

db = SQLAlchemy()
login_manager = LoginManager()
ma = Marshmallow()


@login_manager.user_loader
def load_user(user_id): 
    return User.query.get(user_id)



class User(db.Model, UserMixin):
    id = db.Column(db.String, primary_key = True)
    email = db.Column(db.String(150), nullable = False)
    password = db.Column(db.String, nullable = False)
    token = db.Column(db.String, unique = True)
    date_created = db.Column(db.DateTime, nullable = False, default = datetime.utcnow)
    car = db.relationship('Car', backref='owner', lazy = True)

    def __init__(self, email, password, token = '', id = ''):
        self.id = self.set_id()
        self.email = email
        self.password = self.set_password(password)
        self.token = self.set_token(24)

    def set_id(self):
        return str(uuid.uuid4())
    
    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)
        return self.pw_hash

    def set_token(self, length):
        return secrets.token_hex(length)



class Car(db.Model):
    id = db.Column(db.String, primary_key = True)
    year = db.Column(db.String(4))
    make = db.Column(db.String(30))
    model = db.Column(db.String(30))
    miles = db.Column(db.String(7))
    color = db.Column(db.String(30))
    horsepower = db.Column(db.String(5))
    torque = db.Column(db.String(5))
    modifications = db.Column(db.String(300))
    user_token = db.Column(db.String, db.ForeignKey('user.token'), nullable = False)

    def __init__(self, year, make, model, miles, color,
                horsepower, torque, modifications, user_token, id = ''):
        
        self.id = self.set_id()
        self.year = year
        self.make = make
        self.model = model
        self.miles = miles
        self.color = color
        self.horsepower = horsepower
        self.torque = torque
        self.modifications = modifications
        self.user_token = user_token

    def set_id(self):
        return (secrets.token_urlsafe())


class CarSchema(ma.Schema):
    class Meta:
        fields = ['id', 'year','make', 'model', 'miles', 'color', 'horsepower', 'torque', 'modifications']

car_schema = CarSchema()
cars_schema = CarSchema(many=True)

car_collection/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email

class UserLoginForm(FlaskForm):

    email = StringField('Email', validators = [DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit_button = SubmitField()

car_collection/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from flask_migrate import Migrate
from .models import db, login_manager, ma
from .api.routes import api
from flask_cors import CORS


app = Flask(__name__)
app.config.from_object(Config)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

db.init_app(app)

login_manager.init_app(app)

ma.init_app(app)

login_manager.login_view = 'auth.signin'

migrate = Migrate(app, db)

CORS(app)

car_collection/api/routes.py
from flask import Blueprint, request, jsonify

from car_collection.helpers import token_required
from car_collection.models import User, Car, db, car_schema, cars_schema


api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/getdata')
def getdata():
    return {'some_value': 52, 'another_value': 800}



@api.route('/cars', methods=['POST'])
@token_required
def create_car(current_user_token):
    year = request.json['year']
    make = request.json['make']
    model = request.json['model']
    miles = request.json['miles']
    color = request.json['color']
    horsepower = request.json['horsepower']
    torque = request.json['torque']
    modifications = request.json['modifications']
    token = current_user_token.token

    print(f'TEST: {current_user_token.token}')

    car = Car(year,make,model,miles,color,horsepower,torque,modifications,user_token = token)

    db.session.add(car)
    db.session.commit()

    response = car_schema.dump(car)
    return jsonify(response)



@api.route('/cars', methods = ['Get'])
@token_required
def get_cars(current_user_token):
    owner = current_user_token.token
    cars = Car.query.filter_by(user_token = owner).all()
    response = cars_schema.dump(cars)
    return jsonify(response)



@api.route('/cars/<id>', methods = ['GET'])
@token_required
def get_car(current_user_token, id):
    car = Car.query.get(id)
    response = car_schema.dump(car)
    return jsonify(response)



@api.route('/cars/<id>', methods = ['POST', 'PUT'])
@token_required
def update_car(current_user_token, id):
    car = Car.query.get(id)
    print(car)
    if car:
        car.year = request.json['year']
        car.make = request.json['make']
        car.model = request.json['model']
        car.miles = request.json['miles']
        car.color = request.json['color']
        car.horsepower = request.json['horsepower']
        car.torque = request.json['torque']
        car.modifications = request.json['modifications']
        car.user_token = current_user_token.token
        db.session.commit()

        response = car_schema.dump(car)
        return jsonify(response)
    
    else:
        return jsonify({'Error': 'That car does not exist!'})


@api.route('/drones/<id>', methods = ['DELETE'])
@token_required
def delete_car(current_user_token, id):
    car = Car.query.get(id)
    
    if car:
        db.session.delete(car)
        db.session.commit()
        return jsonify({'Success': f'Car ID # {car.id} has been deleted'})

    else:
        return jsonify({'Error': 'That car does not exist!'})

car_collection/authentication/routes.py
from flask import Blueprint, render_template, request, url_for, flash, redirect
from car_collection.forms import UserLoginForm
from car_collection.models import User, db, check_password_hash
from flask_login import login_user, login_required, logout_user


auth = Blueprint('auth', __name__, template_folder='auth_templates')


@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        


        new_user = User(email, password)
        db.session.add(new_user)
        db.session.commit()

        
        flash(f'You have successfully created an account under {email}', 'user-created')
        
        return redirect(url_for('site.home'))

    return render_template('sign_up.html', form = form)


@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        print(email, password)

        logged_user = User.query.filter(User.email == email).first()
        if logged_user and check_password_hash(logged_user.password, password):
            login_user(logged_user)
            flash('You were successfully logged in.', 'auth-success')
            return redirect(url_for('site.home'))
        else:
            flash('Your Email/Password is incorrect', 'auth-failed')
            return redirect(url_for('auth.signin'))

    return render_template('sign_in.html', form = form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

car_collection/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required

site = Blueprint('site', __name__, template_folder='site_templates')


@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

car_collection/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Car Collection</title>
</head>
<body>

    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('site.home') }}">
                <img src="http://s3.amazonaws.com/gt7sp-prod/decal/32/86/14/4899925203710148632_1.png" alt="" style="width: 80px;">
            </a>
            <h1>Car Collection</h1>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" aria-current="page" href="{{ url_for('site.home') }}">Home</a>
                    {% if current_user.is_authenticated %}
                    <a class="nav-link" href="{{ url_for('site.profile') }}">Profile</a>
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    {% else %}
                    <a class="nav-link btn btn-outline-primary" href="{{ url_for('auth.signin') }}">Sign In</a>
                    <a class="nav-link btn btn-primary" href="{{ url_for('auth.signup') }}">Sign Up Free</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>




    <!-- Block content area... marks the beginning and the end of base-->
    {% block content %}
    {% endblock content %}





<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>